### ISSUE TITLE
is bas compatible with EVM?

### ISSUE THREAD

**Issue by ideafold** [Ankr-network/bas-template-bsc#4]
Thanks for this great repo.

But I have two questions to confirm.
1. is bas compatible with EVM?
2. can user deploy contract in bas?

Thanks

**Comment by dmitry123** [comment]
1. Yes, its fully compatible with Web3 and EVM.
2. You can deploy EVM-compatible smart contract into BAS using Remix, Truffle or any other suitable dev suite.
