### ISSUE TITLE
Has INativeAssetBridge been implemented?

### ISSUE THREAD

**Issue by liyue201** [Ankr-network/bas-template-bsc#5]
First of all, I will say It's great repository. But I can't find the implementation of INativeAssetBridge in the code.

**Comment by dmitry123** [comment]
Hey. Its still under development, here you can find a repository where it'll be located. We're thinking right now how to optimise and simplify native asset bridging. 

https://github.com/Ankr-network/bas-relay-hub

**Comment by dmitry123** [comment]
Also there you can find Parlia validator transition function, but it requires 2/3*N confirmation blocks to verify correctness of the transition. We're thinking of bringing some aggregation here or at least wait for the fast-finality to be implemented by BSC itself. 

https://github.com/Ankr-network/bas-relay-hub/blob/devel/contracts/vierifiers/ParliaBlockVerifier.sol

**Comment by liyue201** [comment]
thanks
